# -*- coding: utf-8 -*-
"""Assign8_GenAI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1s20np81hgQ00PRw2F9TUEWQ3i0-4K3ul
"""

# Install the TTS library and IPython for audio playback
!pip install --upgrade pip
!pip install coqui-tts IPython

import torch
from TTS.api import TTS
from IPython.display import Audio, display

device = "cuda" if torch.cuda.is_available() else "cpu"

# 2. Initialize Tacotron 2 (using the exact string from the registry)
print("Downloading and loading Tacotron model...")
tts = TTS(model_name="tts_models/en/ljspeech/tacotron2-DDC", progress_bar=False).to(device)

print(f"Model successfully loaded on {device}!")

text_input = """
Recent advancements in computer vision and machine learning have opened new possibilities for veterinary care and wildlife monitoring. By analyzing continuous video feeds, artificial intelligence models can now detect subtle changes in animal behavior. For example, identifying signs of physical distress, abnormal pacing, or unusual sleep patterns in large animals can alert caretakers to potential health issues long before a human observer might catch them. This automated monitoring system relies heavily on deep neural networks to extract spatial and temporal features from every single frame.
"""
output_path = "tacotron_output.wav"

print("Generating audio...")
tts.tts_to_file(text=text_input, file_path=output_path)
print("Audio saved!")

display(Audio(output_path))

