# -*- coding: utf-8 -*-
"""Assign2_GenAI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kXwDVCdaXaPNYkQHyza3q4DB8JP_dHYW
"""

!pip install -q -U google-generativeai

import google.generativeai as genai
import os

os.environ["GOOGLE_API_KEY"] = "AIzaSyDv3wXnTz4WdTUiUI_daWskUujsVpmxREg"
genai.configure(api_key=os.environ["GOOGLE_API_KEY"])

# Initialize the model
model = genai.GenerativeModel('gemini-2.5-flash')

def get_completion(prompt, temperature=0.7):
    """
    Helper function to get a response from the model.
    """
    try:
        response = model.generate_content(
            prompt,
            generation_config=genai.types.GenerationConfig(temperature=temperature)
        )
        return response.text.strip()
    except Exception as e:
        return f"Error: {e}"

print("Setup complete. Helper function ready.")

# Zero-Shot Implementation
task_input = "The movie was okay, not great but not terrible."

# In Zero-shot, we just give the instruction and the input.
zero_shot_prompt = f"""
{task_input}
Sentiment:
"""

print("--- Zero-Shot Result ---")
print(get_completion(zero_shot_prompt))

# Cell 4: Few-Shot Implementation

few_shot_prompt = f"""
Determine the sentiment of the sentence.

Input: "The movie was fantastic and thrilling."
Sentiment: Positive

Input: "I wasted 2 hours of my life watching this."
Sentiment: Negative

Input: "The plot was okay, but the acting was mediocre."
Sentiment: Neutral

Input: "The movie was okay, not great but not terrible."
Sentiment:
"""

print("--- Few-Shot Result ---")
print(get_completion(few_shot_prompt))

#The Interview Approach Implementation

def interview_approach(topic):
    history = []

    # Step 1: Set the Persona
    system_instruction = (
        f"You are an expert consultant on {topic}. "
        "Your goal is to write a perfect plan for the user. "
        "Do NOT write the plan yet. First, ask 3 relevant questions to understand the user's specific needs."
    )

    # Initial Trigger
    initial_response = get_completion(system_instruction)
    print(f"AI: {initial_response}\n")

    # Simulate User Answers (In a real app, this would be input())
    user_answers = "1. I am a beginner. 2. I have a budget of $500. 3. I want to learn Python."
    print(f"User: {user_answers}\n")

    # Step 2: Generate Final Output based on Interview
    final_prompt = f"""
    Context: {system_instruction}
    AI Questions: {initial_response}
    User Answers: {user_answers}

    Task: Based on the user's answers, create a detailed step-by-step plan.
    """

    print("--- Final Plan (Post-Interview) ---")
    print(get_completion(final_prompt))

# Run the interview
interview_approach("Learning a New Skill")

# Chain of Thought (CoT) Implementation

standard_prompt = "Roger has 5 tennis balls. He buys 2 more cans of tennis balls. Each can has 3 balls. How many balls does he have now?"

# CoT Prompt (Explicitly asking for reasoning)
cot_prompt = f"""
Question: {standard_prompt}

Let's think step by step.
1. Start with the initial number.
2. Calculate the additions.
3. Sum them up.

Answer:
"""

print("--- Chain of Thought Result ---")
print(get_completion(cot_prompt))

# Simplified Tree of Thoughts (ToT) Implementation

def tree_of_thoughts_solver(problem):
    print(f"Problem: {problem}\n")

    # Step 1: Generate 3 possible first steps (Branches)
    prompt_branches = f"""
    Problem: {problem}
    Propose 3 distinct, different possible first sentences for a story about this problem.
    Label them Option 1, Option 2, and Option 3.
    """
    branches = get_completion(prompt_branches)
    print(f"--- Generated Branches ---\n{branches}\n")

    # Step 2: Evaluate the branches (Self-Reflection)
    prompt_eval = f"""
    Problem: {problem}
    Possible Starts:
    {branches}

    Analyze which option is the most engaging and creative.
    Select the best one and explain why. Output ONLY the number of the best option (e.g., 'Option 1').
    """
    best_option = get_completion(prompt_eval)
    print(f"--- Best Branch Selected ---\n{best_option}\n")

    # Step 3: Expand on the winner
    final_prompt = f"""
    Problem: {problem}
    Selected Start: {best_option}
    Previous Options: {branches}

    Using the text from the selected option, write the complete short story.
    """

    print("--- Final Tree of Thoughts Output ---")
    print(get_completion(final_prompt))

# Run ToT
tree_of_thoughts_solver("A robot discovers it has emotions.")

