# -*- coding: utf-8 -*-
"""Assign1_GenAI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t8CHpNRwdQOV4pTHNH9KeT8VQJbCZKDv
"""

import random
from collections import defaultdict

text = """
markov chains are useful for text generation
they predict the next word based on the previous word
this is a simple markov chain example
"""

words = text.lower().split()
words

markov_chain = defaultdict(list)

for i in range(len(words) - 1):
    current_word = words[i]
    next_word = words[i + 1]
    markov_chain[current_word].append(next_word)

markov_chain

def generate_text(chain, start_word, length=20):
    word = start_word
    result = [word]

    for _ in range(length - 1):
        if word not in chain:
            break
        word = random.choice(chain[word])
        result.append(word)

    return " ".join(result)

start_word = "markov"
generated_text = generate_text(markov_chain, start_word, length=50)
generated_text

for i in range(3):
    print(generate_text(markov_chain, start_word, length=20))