# -*- coding: utf-8 -*-
"""GenAI_Lab4_VaishnaviKhade.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XjnElYti7qLRkNP8muLnCFf98OsOdQR2

**Build a simple question-answering chatbot using a pre-trained language model.**

## 1. Problem Statement

* Many users require quick access to information through conversational systems.
* Traditional systems require users to manually search through documents or websites.
* There is a need for an **interactive chatbot** that can answer user questions automatically.
* The system should be able to **understand natural language questions and provide relevant answers**.
* The chatbot should also support **basic greetings like "hi", "hello", and "good morning"** to make the interaction more natural.

---

## 2. Objective

* To develop a **simple chatbot using a pre-trained Natural Language Processing model**.
* To allow users to ask questions related to **clothing according to different seasons**.
* To extract the **most relevant answers from a given context paragraph**.
* To demonstrate how **Generative AI and NLP models** can be used for building conversational systems.
* To integrate **basic conversational responses along with AI-based question answering**.

---

## 3. Theory

* A **chatbot** is a software application that can communicate with users through text or voice.
* Chatbots use **Natural Language Processing (NLP)** to understand user input and generate appropriate responses.
* Modern chatbots often use **pre-trained language models** that are trained on large datasets.
* In this project, a **Question Answering (QA) model** is used to extract answers from a predefined context.
* The model used is **DistilBERT Question Answering model**, which is trained on the SQuAD dataset.
* The model is implemented using the **Hugging Face Transformers library**, which provides easy-to-use NLP pipelines.
* When a user asks a question, the system compares the **question with the given context text** and finds the most relevant answer.
* The chatbot also includes **rule-based responses for greetings** such as *hi, hello, and good morning*.
* If the user enters a greeting, the chatbot responds with a predefined message.
* If the user asks a question related to the topic, the QA model **extracts the best possible answer from the context**.
* This approach combines **rule-based logic and machine learning models** to build an intelligent chatbot system.

---

## 4. Methodology

1. Install required Python libraries such as **Transformers and PyTorch**.
2. Load a **pre-trained Question Answering model**.
3. Provide a **context paragraph containing information about seasonal clothing**.
4. Accept user input in the form of a question.
5. Check if the input is a greeting and respond with a predefined message.
6. If the input is a question, send it to the QA model along with the context.
7. The model analyzes the question and extracts the **most relevant answer from the context text**.
8. Display the chatbot response to the user in a conversational format.

---

## 5. Tech Stack

* **Programming Language:** Python
* **Libraries:** Transformers, PyTorch
* **Model:** DistilBERT Question Answering Model
* **Framework:** Hugging Face Transformers
* **Development Environment:** Google Colab / Jupyter Notebook

---

## 6. Conclusion

* A chatbot was successfully implemented using a **pre-trained question answering model**.
* The system can respond to **basic greetings and answer user questions based on a given context**.
* The use of pre-trained models reduces the need for training large datasets.
* The chatbot demonstrates the **practical application of NLP and Generative AI in conversational systems**.
* This approach can be extended to build **customer support chatbots, virtual assistants, and information retrieval systems**.

---

✅ **Tip for Colab structure (best for submission):**

Cell 1 → Title + Theory (Markdown)
Cell 2 → Install libraries
Cell 3 → Chatbot code
Cell 4 → Sample Output

---

If you want, I can also give you a **very clean Colab notebook structure teachers love (with headings and formatting)** so your assignment looks **more professional.**
"""

# install libraries
!pip install transformers torch

from transformers import pipeline

# Load QA model
qa = pipeline("question-answering", model="distilbert-base-cased-distilled-squad")

# Context (~1000 words)
context = """
Clothing choices often change depending on the season. Each season has its own weather
conditions, and people select clothes that help them stay comfortable and healthy.
Understanding what to wear in different seasons can help individuals stay cool in summer,
warm in winter, and protected during rainy periods.

During the summer season, the weather is usually hot and sometimes humid. Because of
the high temperature, people prefer to wear light and breathable fabrics. Cotton is
one of the most popular materials during summer because it absorbs sweat and allows
air to circulate through the fabric. Loose-fitting clothing is also recommended during
summer because it helps the body stay cool. Common summer clothing includes T-shirts,
shorts, skirts, light dresses, and sandals. Light colors such as white, beige, and
pastel shades are often preferred because they reflect sunlight rather than absorbing
heat. Wearing hats, sunglasses, and lightweight scarves can also protect the skin
from direct sunlight.

In addition to comfort, summer clothing should also provide protection from the sun.
Many people wear caps or wide-brimmed hats when spending time outdoors. Sunglasses
help protect the eyes from strong sunlight and ultraviolet rays. Breathable footwear
such as sandals or canvas shoes helps keep feet cool during hot days.

The winter season is very different from summer because the temperature becomes
much colder. During winter, people need clothing that provides warmth and insulation.
Wool is a commonly used material because it traps body heat and keeps the wearer
warm. Sweaters, jackets, coats, scarves, gloves, and woolen socks are typical winter
clothing items. Layering is an important technique used in winter clothing. Instead
of wearing a single thick garment, people often wear several layers of clothing.

Layering helps trap warm air between clothing layers, which improves insulation.
Winter coats are often designed to block cold wind and retain heat. Accessories
such as scarves and gloves are also important because they protect sensitive parts
of the body like the neck and hands from cold weather.

The rainy season requires clothing that protects the body from rain and moisture.
Waterproof materials are very useful during this season. Raincoats, umbrellas,
and waterproof jackets are commonly used. Many people also wear rubber boots or
waterproof shoes to keep their feet dry.

During rainy weather, it is better to avoid heavy fabrics because they absorb
water and take a long time to dry. Lightweight synthetic materials such as
polyester or nylon are often preferred because they dry faster.

Spring and autumn are transitional seasons between summer and winter. The weather
during these seasons is usually mild but can change quickly. People often wear
light layers such as jackets or cardigans that can easily be added or removed.

Choosing appropriate clothing for each season is important for comfort, health,
and protection from environmental conditions.
"""

print("Seasonal Clothing Chatbot Ready! Type 'exit' to stop.\n")

# Greeting responses
greetings = {
    "hi": "Hello! How can I help you today?",
    "hello": "Hi there! Ask me anything about seasonal clothing.",
    "hey": "Hey! What would you like to know about clothes for different seasons?",
    "good morning": "Good morning! How can I assist you today?",
    "good afternoon": "Good afternoon! Feel free to ask about seasonal clothing.",
    "good evening": "Good evening! What would you like to know?"
}

# Chat loop
while True:

    question = input("You: ").lower()

    if question == "exit":
        print("Chatbot: Goodbye! Have a nice day!")
        break

    # Greeting detection
    if question in greetings:
        print("Chatbot:", greetings[question])
        print()
        continue

    # Question answering
    result = qa(question=question, context=context)

    print("Chatbot:", result["answer"])
    print()