# -*- coding: utf-8 -*-
"""Assign7_GenAI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_CGhnNrS7uyJTDFE3CgsymKW-To9c77R
"""

!pip install transformers torch pillow

import torch
from PIL import Image
from transformers import CLIPProcessor, CLIPModel

# Set device
device = "cuda" if torch.cuda.is_available() else "cpu"

# Load the model and processor
model_id = "openai/clip-vit-base-patch32"
model = CLIPModel.from_pretrained(model_id).to(device)
processor = CLIPProcessor.from_pretrained(model_id)

print(f"Model loaded on {device}")

from PIL import Image

# 1. Load a local image file
image_path = "/content/Image.jpg"

try:
    image = Image.open(image_path).convert("RGB")
    print(f"Image successfully loaded from {image_path}!")
    display(image)
except FileNotFoundError:
    print(f"Error: Image file not found at {image_path}")
except Exception as e:
    print(f"An error occurred while loading the image: {e}")

# 4. Define "candidate" captions
candidate_captions = [
    "a photo of a lush green forest with a river",
    "a bustling city street at night with neon lights",
    "a close up of a delicious chocolate cake",
    "a snowy mountain peak under a blue sky",
    "a portrait of a golden retriever dog"
]

# Process inputs
inputs = processor(
    text=candidate_captions,
    images=image,
    return_tensors="pt",
    padding=True
).to(device)

# Forward pass
with torch.no_grad():
    outputs = model(**inputs)

# Get the similarity scores (logits)
# logits_per_image is the similarity between the image and each text
probs = outputs.logits_per_image.softmax(dim=1)

# Find the index of the highest probability
best_idx = probs.argmax().item()

print(f"Top Caption: {candidate_captions[best_idx]}")
print(f"Confidence: {probs[0][best_idx].item():.2%}")

