# -*- coding: utf-8 -*-
"""Assign9_GenAI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18WTcsRG2jT-3vcd7QVcfxEl-R8KTf8Ye
"""

!pip install diffusers transformers accelerate imageio

import torch
from diffusers import AnimateDiffPipeline, MotionAdapter, DDIMScheduler
from diffusers.utils import export_to_gif

# 1. Load the motion adapter (this teaches the static model how things move over time)
adapter = MotionAdapter.from_pretrained(
    "guoyww/animatediff-motion-adapter-v1-5-2",
    torch_dtype=torch.float16
)

# 2. Load the base Stable Diffusion model and combine it with the adapter
pipe = AnimateDiffPipeline.from_pretrained(
    "runwayml/stable-diffusion-v1-5",
    motion_adapter=adapter,
    torch_dtype=torch.float16
)

# 3. Set a specific scheduler optimized for video
pipe.scheduler = DDIMScheduler.from_config(
    pipe.scheduler.config,
    clip_sample=False,
    timestep_spacing="linspace",
    steps_offset=1
)

# 4. Memory Optimization (Crucial for avoiding crashes on standard GPUs)
pipe.enable_model_cpu_offload()
pipe.enable_vae_slicing()

print("Video pipeline successfully loaded!")

prompt = "A cinematic low-angle drone shot of a futuristic smart farm at sunrise. Green crops in perfect rows. A small, sleek autonomous robot with blue glowing lights is slowly moving between the rows watering plants. Golden hour lighting, lens flare, 4k resolution, highly detailed, slow smooth motion."
negative_prompt = "bad quality, distorted, static, motionless, low resolution"

print("Generating frames... (This may take a few minutes depending on your hardware)")

output = pipe(
    prompt=prompt,
    negative_prompt=negative_prompt,
    num_frames=16,
    guidance_scale=7.5,
    num_inference_steps=25,
)

# 3. Export the resulting frames to a viewable format
gif_path = "simple_animation.gif"
export_to_gif(output.frames[0], gif_path)

print(f"Animation saved successfully as {gif_path}!")

from IPython.display import Image
display(Image(open(gif_path, 'rb').read()))

