# -*- coding: utf-8 -*-
"""GenAI_Lab6_VaishnaviKhade.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1InTIC1CLu8StFKBDRHgmeGeCtoHVw-IL

**Create a text-to-image generation pipeline using a pre-trained model like DALL-E.**

# Problem Statement

* Generating images manually requires artistic skills and significant time.
* Users may want to create images simply by describing them in natural language.
* Traditional software cannot automatically convert text descriptions into images.
* Therefore, there is a need for a system that can **generate images directly from textual prompts using AI models**.

---

# Objective

* To build a **text-to-image generation pipeline** using a pre-trained generative model.
* To allow users to input a **text prompt describing a scene or object**.
* To generate a **realistic image corresponding to the text description**.
* To demonstrate the use of modern **Generative AI techniques for visual content creation**.

---

# Theory

* **Text-to-image generation** is a technique in Generative AI that converts text descriptions into images.
* It uses **deep learning models trained on large datasets containing image-text pairs**.
* These models learn how words relate to visual features such as objects, colors, and environments.
* In this project, a **diffusion-based generative model** is used. Diffusion models start with random noise and gradually refine it to produce a realistic image.
* The text prompt is first converted into numerical **text embeddings** using a text encoder.
* The diffusion model then uses these embeddings to guide the image generation process.
* The implementation uses the **Stable Diffusion model**, which is widely used for generating high-quality images.
* Libraries such as **Diffusers and PyTorch** make it easier to load and run these pre-trained models.
* When a user enters a prompt such as *“A beautiful sunrise over a lake”*, the system interprets the text and generates a corresponding image.
* This technology is widely used in **digital art generation, gaming, advertising, media production, and content creation**.

---

# Methodology

1. Install the required libraries such as **Diffusers, Transformers, and PyTorch**.
2. Import necessary Python modules for image generation.
3. Load a **pre-trained Stable Diffusion model** from the model repository.
4. Provide a **text prompt as input** describing the image to be generated.
5. The model converts the prompt into **text embeddings**.
6. The diffusion process gradually generates an image based on the prompt.
7. The generated image is displayed as output in the notebook.

---

# Tech Stack

* **Programming Language:** Python
* **Libraries:** Diffusers, Transformers, PyTorch
* **Model:** Stable Diffusion
* **Environment:** Google Colab / Jupyter Notebook
* **Hardware Support:** GPU for faster image generation

---

# Conclusion

* The project successfully demonstrates **text-to-image generation using a pre-trained diffusion model**.
* The system can generate images from simple natural language descriptions.
* Pre-trained models eliminate the need for training from scratch on large datasets.
* The project highlights the potential of **Generative AI in creating visual content automatically**.
* Such systems can be applied in **art generation, media design, education, and entertainment industries**.

---

If you want, I can also give you a **perfect Colab notebook structure (with headings and code blocks)** so your assignment looks **very clean and professional when submitted.**
"""

!pip -q install diffusers transformers accelerate torch safetensors

import torch
from diffusers import StableDiffusionPipeline
from IPython.display import display

model_id = "runwayml/stable-diffusion-v1-5"

pipe = StableDiffusionPipeline.from_pretrained(
    model_id,
    torch_dtype=torch.float16
)

pipe = pipe.to("cuda")

prompt = "A beautiful sunset over a calm lake with orange and pink sky, mountains in background, reflection in water, realistic photography"

image = pipe(prompt).images[0]

display(image)

prompt = "A stunning sunset over a peaceful lake, golden sunlight reflecting on the water, colorful clouds in the sky, mountains in the background, ultra realistic, 4k landscape photography"

image = pipe(prompt).images[0]

display(image)

prompt = "Golden sunrise over a mountain lake with fog and trees, beautiful morning light, reflection on water, high detail nature photography"
image = pipe(prompt).images[0]
display(image)